name: c_processor
description: Um processador para um subconjunto da linguagem C para o trabalho final de Compiladores.
version: 0.0.1
homepage: https://github.com/vitorhhiguchi/trabalho-final-compiladores

environment:
  sdk: '>=3.0.0 <4.0.0'

# Define o executável para rodar pela linha de comando [cite: 20]
executables:
  c_processor: # Nome do executável
    
dependencies:
  # Runtime do ANTLR para Dart
  antlr4: ^4.13.1 # Verifique a versão mais recente no pub.dev

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0